"""initial schema

Revision ID: 11f898df57c9
Revises: 
Create Date: 2026-08-12 19:07:55.032423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f898df57c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harness_versions',
    sa.Column('scope', sa.String(length=160), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('yaml', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'id', 'version')
    )
    op.create_table('harnesses',
    sa.Column('scope', sa.String(length=160), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('yaml', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'id')
    )
    op.create_table('team_members',
    sa.Column('team_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('handle', sa.String(length=128), nullable=False),
    sa.Column('token_sha', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_token_sha'), 'users', ['token_sha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_token_sha'), table_name='users')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('team_members')
    op.drop_table('harnesses')
    op.drop_table('harness_versions')
    # ### end Alembic commands ###
