"""authoring 테이블: app_settings + user_components(+versions)

Revision ID: 483f355db5fe
Revises: c3d4e5f6a7b8
Create Date: 2026-08-14 17:20:17.910586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483f355db5fe'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('llm_key_enc', sa.Text(), nullable=False),
    sa.Column('embedding_key_enc', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_component_versions',
    sa.Column('scope', sa.String(length=160), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'id', 'version')
    )
    op.create_table('user_components',
    sa.Column('scope', sa.String(length=160), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'id')
    )
    op.create_index(op.f('ix_user_components_type'), 'user_components', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_components_type'), table_name='user_components')
    op.drop_table('user_components')
    op.drop_table('user_component_versions')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
