"""app_settings search_key

Revision ID: 5d5984e8d30c
Revises: e88ef4a4cd6e
Create Date: 2026-08-18 15:41:19.775775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5984e8d30c'
down_revision: Union[str, Sequence[str], None] = 'e88ef4a4cd6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('search_key_enc', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'search_key_enc')
    # ### end Alembic commands ###
