"""studio conversations

Revision ID: e88ef4a4cd6e
Revises: 483f355db5fe
Create Date: 2026-08-14 19:01:47.422643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88ef4a4cd6e'
down_revision: Union[str, Sequence[str], None] = '483f355db5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studio_conversations',
    sa.Column('scope', sa.String(length=160), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('draft', sa.Text(), nullable=False),
    sa.Column('draft_type', sa.String(length=16), nullable=False),
    sa.Column('component_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'id')
    )
    op.create_index(op.f('ix_studio_conversations_updated_at'), 'studio_conversations', ['updated_at'], unique=False)
    op.create_table('studio_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=160), nullable=False),
    sa.Column('conversation_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_messages_conversation_id'), 'studio_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_studio_messages_scope'), 'studio_messages', ['scope'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studio_messages_scope'), table_name='studio_messages')
    op.drop_index(op.f('ix_studio_messages_conversation_id'), table_name='studio_messages')
    op.drop_table('studio_messages')
    op.drop_index(op.f('ix_studio_conversations_updated_at'), table_name='studio_conversations')
    op.drop_table('studio_conversations')
    # ### end Alembic commands ###
